/*** User signin/signup/signout ***/
export const USER_SIGN_UP_START = 'USER_SIGN_UP_START';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_SIGN_UP_FAILURE = 'USER_SIGN_UP_FAILURE';
export const USER_SIGN_IN_START = 'USER_SIGN_IN_START';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_FAILURE = 'USER_SIGN_IN_FAILURE';
export const USER_SIGN_OUT = 'USER_SIGN_OUT';
export const FACEBOOK_LOGIN_START = 'FACEBOOK_LOGIN_START';
export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';

/*** Profile Update ***/
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILURE = 'PROFILE_UPDATE_FAILURE';

/*** Post Create ***/
export const POST_UPLOAD_START = 'POST_UPLOAD_START';
export const POST_UPLOAD_SUCCESS = 'POST_UPLOAD_SUCCESS';
export const POST_UPLOAD_FAILURE = 'POST_UPLOAD_FAILURE';

/*** Fetch Posts ***/
export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

export const FETCH_POSTS_BY_LOCATION_SUCCESS = 'FETCH_POSTS_BY_LOCATION_SUCCESS';
export const FETCH_POSTS_BY_LOCATION_FAILURE = 'FETCH_POSTS_BY_LOCATION_FAILURE';

export const FETCH_POSTS_BY_TAG_SUCCESS = 'FETCH_POSTS_BY_TAG_SUCCESS';
export const FETCH_POSTS_BY_TAG_FAILURE = 'FETCH_POSTS_BY_TAG_FAILURE';
/*** Post Like ***/
export const LIKE_POST = 'LIKE_POST';
export const DISLIKE_POST = 'DISLIKE_POST';

/*** Post Comments ***/
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';

/*** Public Profile ***/
export const FETCH_PUBLIC_PROFILE_START = 'FETCH_PUBLIC_PROFILE_START';
export const FETCH_PUBLIC_PROFILE_SUCCESS = 'FETCH_PUBLIC_PROFILE_SUCCESS';
export const FETCH_PUBLIC_PROFILE_FAILURE = 'FETCH_PUBLIC_PROFILE_FAILURE';
export const FETCH_POSTS_BY_USERNAME_START = 'FETCH_POSTS_BY_USERNAME_START';
export const FETCH_POSTS_BY_USERNAME_SUCCESS = 'FETCH_POSTS_BY_USERNAME_SUCCESS';
export const FETCH_POSTS_BY_USERNAME_FAILURE = 'FETCH_POSTS_BY_USERNAME_FAILURE';

/*** Follow Users ***/
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';

/*** Fetch Followers/Following ***/
export const FETCH_FOLLOWERS_START = 'FETCH_FOLLOWERS_START';
export const FETCH_FOLLOWERS_SUCCESS = 'FETCH_FOLLOWERS_SUCCESS';
export const FETCH_FOLLOWERS_FAILURE = 'FETCH_FOLLOWERS_FAILURE';
export const FETCH_FOLLOWING_START = 'FETCH_FOLLOWING_START';
export const FETCH_FOLLOWING_SUCCESS = 'FETCH_FOLLOWING_SUCCESS';
export const FETCH_FOLLOWING_FAILURE = 'FETCH_FOLLOWING_FAILURE';

/*** Fetch Likers ***/
export const FETCH_LIKERS_START = 'FETCH_LIKERS_START';
export const FETCH_LIKERS_SUCCESS = 'FETCH_LIKERS_SUCCESS';
export const FETCH_LIKERS_FAILURE = 'FETCH_LIKERS_FAILURE';

/*** Fetch Notifications ***/
export const FETCH_NOTIFICATIONS_START = 'FETCH_NOTIFICATIONS_START';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAILURE = 'FETCH_NOTIFICATIONS_FAILURE';

export const FETCH_NOTIFICATION_COUNT = 'FETCH_NOTIFICATION_COUNT';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';
export const TOUCH_NOTIFICATION = 'TOUCH_NOTIFICATION';
export const LIKE_POST_NOTIFICATION_RECEIVED = 'LIKE_POST_NOTIFICATION_RECEIVED';
export const START_FOLLOWING_NOTIFICATION_RECEIVED = 'START_FOLLOWING_NOTIFICATION_RECEIVED';
export const COMMENT_ON_POST_NOTIFICATION_RECEIVED = 'COMMENT_ON_POST_NOTIFICATION_RECEIVED';
export const HIDE_NEW_NOTIFICATION = 'HIDE_NEW_NOTIFICATION';

/*** Fetch more comments ***/
export const FETCH_MORE_COMMENTS_SUCCUESS = 'FETCH_MORE_COMMENTS_SUCCUESS';

/*** Fetch follow suggestions ***/
export const FETCH_FOLLOW_SUGGESTIONS_START = 'FETCH_FOLLOW_SUGGESTIONS_START';
export const FETCH_FOLLOW_SUGGESTIONS_SUCCESS = 'FETCH_FOLLOW_SUGGESTIONS_SUCCESS';
export const FETCH_FOLLOW_SUGGESTIONS_FAILURE = 'FETCH_FOLLOW_SUGGESTIONS_FAILURE';
