/*** User signin/signup/signout ***/
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_SIGN_UP_FAILURE = 'USER_SIGN_UP_FAILURE';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_FAILURE = 'USER_SIGN_IN_FAILURE';
export const USER_SIGN_OUT = 'USER_SIGN_OUT';

/*** Profile Update ***/
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILURE = 'PROFILE_UPDATE_FAILURE';

/*** Post Create ***/
export const POST_UPLOAD_START = 'POST_UPLOAD_START';
export const POST_UPLOAD_SUCCESS = 'POST_UPLOAD_SUCCESS';
export const POST_UPLOAD_FAILURE = 'POST_UPLOAD_FAILURE';

/*** Fetch Posts ***/
export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

/*** Post Like ***/
export const LIKE_POST = 'LIKE_POST';
export const DISLIKE_POST = 'DISLIKE_POST';

/*** Post Comments ***/
export const ADD_COMMENT = 'ADD_COMMENT';

/*** Public Profile ***/
export const FETCH_PUBLIC_PROFILE_START = 'FETCH_PUBLIC_PROFILE_START';
export const FETCH_PUBLIC_PROFILE_SUCCESS = 'FETCH_PUBLIC_PROFILE_SUCCESS';
export const FETCH_PUBLIC_PROFILE_FAILURE = 'FETCH_PUBLIC_PROFILE_FAILURE';
export const FETCH_POSTS_BY_USERNAME_START = 'FETCH_POSTS_BY_USERNAME_START';
export const FETCH_POSTS_BY_USERNAME_SUCCESS = 'FETCH_POSTS_BY_USERNAME_SUCCESS';
export const FETCH_POSTS_BY_USERNAME_FAILURE = 'FETCH_POSTS_BY_USERNAME_FAILURE';

/*** Follow Users ***/
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
